services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: ats_postgres_db
    environment:
      POSTGRES_DB: ats_db
      POSTGRES_USER: ats_user
      POSTGRES_PASSWORD: ats_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ats_user -d ats_db"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
