### 0. Înregistrare Utilizator Nou (POST)
POST http://localhost:8080/api/v1/auth/register
Content-Type: application/json

{
  "email": "sarbu.mihai@gmail.com",
  "password": "ParolaSecurizata123!",
  "fullName": "Alexandru Sîrbu"
}

### 0.1 Autentificare Utilizator & Obținere Token JWT (POST)
POST http://localhost:8080/api/v1/auth/login
Content-Type: application/json

{
  "email": "sarbu.mihai@gmail.com",
  "password": "ParolaSecurizata123!"
}

### 1. Salvează un Job Nou (POST)
POST http://localhost:8080/api/v1/jobs
Content-Type: application/json
X-User-Id: a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11

{
  "companyName": "Google",
  "jobTitle": "Junior Backend Developer",
  "jobUrl": "https://careers.google.com/jobs/123",
  "rawDescription": "Căutăm un Junior Backend Developer pasionat de Java 21, Spring Boot și baze de date PostgreSQL. Experiență cu Docker și AWS reprezintă un plus."
}

### 2. Încărcare CV PDF (POST Multipart)
POST http://localhost:8080/api/v1/resumes
X-User-Id: a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="cv_alex.pdf"
Content-Type: application/pdf

< ./sample_cv.pdf
--WebAppBoundary--

### 3. Creează o Aplicație & Calculează Match Score (POST)
POST http://localhost:8080/api/v1/applications
Content-Type: application/json
X-User-Id: a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11

{
  "jobId": "259ee173-c091-4e0b-90a2-a29f5c65d315",
  "resumeId": "e9002a06-b07d-460b-a82a-e23fdb3fbefb",
  "notes": "Am aplicat direct pe portalul oficial Google Careers."
}

### 4. Generează Raportul AI Gap Analysis & Planul de Acțiune (POST)
POST http://localhost:8080/api/v1/applications/fa9639cb-deee-4848-8dbf-a6e3b83812a1/analysis
